# Generated by Django 2.2.4 on 2019-10-23 14:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APISite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('howToUse', models.TextField()),
                ('maxRequestCount', models.TextField()),
                ('expiredDate', models.TextField()),
                ('contributors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('howToUse', models.TextField()),
                ('maxRequestCount', models.TextField()),
                ('expiredDate', models.TextField()),
                ('requestUser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('rating_date', models.CharField(max_length=200)),
                ('apiSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.APISite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('howToUse', models.TextField()),
                ('maxRequestCount', models.TextField()),
                ('expiredDate', models.TextField()),
                ('requestUser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.APISite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
