# Generated by Django 2.2.4 on 2019-10-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisite',
            name='needAuthentication',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editedlist',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editedlist',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editedlist',
            name='needAuthentication',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerlist',
            name='needAuthentication',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EndPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAuthentication', models.BooleanField()),
                ('pathParams', models.TextField()),
                ('queryString', models.TextField()),
                ('response', models.TextField()),
                ('apisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.APISite')),
            ],
        ),
    ]
