# Generated by Django 2.2.4 on 2019-11-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191029_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('code', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='apisite',
            name='needAuthentication',
        ),
        migrations.RemoveField(
            model_name='editedlist',
            name='needAuthentication',
        ),
        migrations.RemoveField(
            model_name='registerlist',
            name='needAuthentication',
        ),
    ]
